name: Hello World Workflow1

on:
  push:
    branches: [main]

jobs:
  say-hello123:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Print Hello World2
        run: echo "Hello, world!"

      - name: Say another message3
        run: echo "GitHub Actions are running 🚀"

      - name: Show current directory4
        run: pwd

      - name: List files in repo5
        run: ls -la

      - name: Running the Application
        run: python3 hello.py
